// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBkZgLlvIazPi7hfIA--uOPgmLhspP94c',
    appId: '1:473259466067:web:e59977afa5fd6783d455a6',
    messagingSenderId: '473259466067',
    projectId: 'soil-sensor-mapper',
    authDomain: 'soil-sensor-mapper.firebaseapp.com',
    storageBucket: 'soil-sensor-mapper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-RxrCtdcfxUGFoyIqTdPniZOSh2oppk',
    appId: '1:473259466067:android:0198f1d064f30cbdd455a6',
    messagingSenderId: '473259466067',
    projectId: 'soil-sensor-mapper',
    storageBucket: 'soil-sensor-mapper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA36OwjtJRwjQHoo37Vy6AZ95kmpGg6eM',
    appId: '1:473259466067:ios:360e559ec7ad3516d455a6',
    messagingSenderId: '473259466067',
    projectId: 'soil-sensor-mapper',
    storageBucket: 'soil-sensor-mapper.appspot.com',
    iosBundleId: 'com.example.sensorMapping',
  );
}
